use std::time::Duration;

use serde::{Deserialize, Serialize};
use tower_acc::{Aimd, Algorithm, Gradient2, Vegas};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SimConfig {
    /// Total simulation duration in seconds.
    #[serde(default = "default_duration")]
    pub duration_secs: f64,

    /// Average requests per second generated by the client.
    #[serde(default = "default_rps")]
    pub request_rate: f64,

    /// Server-side ACC algorithm.
    #[serde(default = "default_server_algorithm")]
    pub server_algorithm: AlgorithmConfig,

    /// Client-side ACC algorithm.
    #[serde(default = "default_client_algorithm")]
    pub client_algorithm: AlgorithmConfig,

    /// Maximum queue depth before load shedding.
    #[serde(default = "default_queue_capacity")]
    pub queue_capacity: usize,

    /// Latency regimes (time-ordered). The first regime starts at t=0.
    #[serde(default = "default_regimes")]
    pub regimes: Vec<LatencyRegimeConfig>,

    /// RNG seed for deterministic runs.
    #[serde(default = "default_seed")]
    pub seed: u64,
}

impl Default for SimConfig {
    fn default() -> Self {
        serde_json::from_str("{}").unwrap()
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum AlgorithmConfig {
    Aimd {
        #[serde(default = "default_initial_limit")]
        initial_limit: usize,
        #[serde(default = "default_aimd_min_limit")]
        min_limit: usize,
        #[serde(default = "default_aimd_max_limit")]
        max_limit: usize,
        #[serde(default = "default_backoff_ratio")]
        backoff_ratio: f64,
        #[serde(default = "default_timeout_ms")]
        timeout_ms: u64,
    },
    Gradient2 {
        #[serde(default = "default_initial_limit")]
        initial_limit: usize,
        #[serde(default = "default_gradient2_min_limit")]
        min_limit: usize,
        #[serde(default = "default_gradient2_max_limit")]
        max_limit: usize,
        #[serde(default = "default_gradient2_smoothing")]
        smoothing: f64,
        #[serde(default = "default_rtt_tolerance")]
        rtt_tolerance: f64,
        #[serde(default = "default_long_window")]
        long_window: usize,
    },
    Vegas {
        #[serde(default = "default_initial_limit")]
        initial_limit: usize,
        #[serde(default = "default_vegas_max_limit")]
        max_limit: usize,
        #[serde(default = "default_smoothing")]
        smoothing: f64,
    },
}

impl AlgorithmConfig {
    pub fn build(&self) -> Box<dyn Algorithm> {
        match self {
            AlgorithmConfig::Vegas {
                initial_limit,
                max_limit,
                smoothing,
            } => Box::new(
                Vegas::builder()
                    .initial_limit(*initial_limit)
                    .max_limit(*max_limit)
                    .smoothing(*smoothing)
                    .build(),
            ),
            AlgorithmConfig::Aimd {
                initial_limit,
                min_limit,
                max_limit,
                backoff_ratio,
                timeout_ms,
            } => Box::new(
                Aimd::builder()
                    .initial_limit(*initial_limit)
                    .min_limit(*min_limit)
                    .max_limit(*max_limit)
                    .backoff_ratio(*backoff_ratio)
                    .timeout(Duration::from_millis(*timeout_ms))
                    .build(),
            ),
            AlgorithmConfig::Gradient2 {
                initial_limit,
                min_limit,
                max_limit,
                smoothing,
                rtt_tolerance,
                long_window,
            } => Box::new(
                Gradient2::builder()
                    .initial_limit(*initial_limit)
                    .min_limit(*min_limit)
                    .max_limit(*max_limit)
                    .smoothing(*smoothing)
                    .rtt_tolerance(*rtt_tolerance)
                    .long_window(*long_window)
                    .build(),
            ),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LatencyRegimeConfig {
    /// Time offset in seconds when this regime begins.
    pub start_secs: f64,

    /// Mean latency in milliseconds (log-normal mu parameter derived from this).
    pub mean_latency_ms: f64,

    /// Standard deviation factor for log-normal distribution (sigma).
    #[serde(default = "default_latency_std")]
    pub std_factor: f64,
}

// Default value functions
fn default_duration() -> f64 {
    60.0
}
fn default_rps() -> f64 {
    200.0
}
fn default_seed() -> u64 {
    42
}
fn default_initial_limit() -> usize {
    20
}
fn default_vegas_max_limit() -> usize {
    200
}
fn default_smoothing() -> f64 {
    1.0
}
fn default_aimd_min_limit() -> usize {
    10
}
fn default_aimd_max_limit() -> usize {
    200
}
fn default_backoff_ratio() -> f64 {
    0.9
}
fn default_timeout_ms() -> u64 {
    1500
}
fn default_gradient2_min_limit() -> usize {
    20
}
fn default_gradient2_max_limit() -> usize {
    200
}
fn default_gradient2_smoothing() -> f64 {
    0.2
}
fn default_rtt_tolerance() -> f64 {
    1.5
}
fn default_long_window() -> usize {
    600
}
fn default_queue_capacity() -> usize {
    100
}
fn default_latency_std() -> f64 {
    0.3
}

fn default_server_algorithm() -> AlgorithmConfig {
    AlgorithmConfig::Gradient2 {
        initial_limit: default_initial_limit(),
        min_limit: default_gradient2_min_limit(),
        max_limit: default_gradient2_max_limit(),
        smoothing: default_gradient2_smoothing(),
        rtt_tolerance: default_rtt_tolerance(),
        long_window: default_long_window(),
    }
}

fn default_client_algorithm() -> AlgorithmConfig {
    AlgorithmConfig::Aimd {
        initial_limit: default_initial_limit(),
        min_limit: default_aimd_min_limit(),
        max_limit: default_aimd_max_limit(),
        backoff_ratio: default_backoff_ratio(),
        timeout_ms: default_timeout_ms(),
    }
}

fn default_regimes() -> Vec<LatencyRegimeConfig> {
    vec![
        // 1. Easy cruising — low latency, everything healthy.
        LatencyRegimeConfig {
            start_secs: 0.0,
            mean_latency_ms: 50.0,
            std_factor: 0.3,
        },
        // 2. Moderate stress — limits climb, some queuing but manageable.
        LatencyRegimeConfig {
            start_secs: 10.0,
            mean_latency_ms: 150.0,
            std_factor: 0.4,
        },
        // 3. Recovery — latency drops, limits readjust down, queue drains.
        LatencyRegimeConfig {
            start_secs: 20.0,
            mean_latency_ms: 50.0,
            std_factor: 0.3,
        },
        // 4. Dramatic spike — high latency + fat tails overwhelm the system,
        //    queue fills up, shedding kicks in.
        LatencyRegimeConfig {
            start_secs: 30.0,
            mean_latency_ms: 500.0,
            std_factor: 0.8,
        },
        // 5. Stressed but stable — queue partially full but not shedding.
        LatencyRegimeConfig {
            start_secs: 42.0,
            mean_latency_ms: 250.0,
            std_factor: 0.35,
        },
        // 6. Back to easy — full recovery.
        LatencyRegimeConfig {
            start_secs: 52.0,
            mean_latency_ms: 50.0,
            std_factor: 0.3,
        },
    ]
}
